{% set name = 'ctgan' %}
{% set version = '0.4.0.dev2' %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"

build:
  number: 0
  noarch: python
  entry_points:
    - ctgan=ctgan.__main__:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - pytest-runner
    - packaging
    - python >=3.6,<3.9
    - numpy >=1.18.0,<2
    - pandas >=1.1,<1.1.5
    - scikit-learn >=0.23,<1
    - pytorch >=1.4,<2
    - torchvision >=0.5.0,<1
    - rdt >=0.2.10,<0.5
  run:
    - packaging
    - python >=3.6,<3.9
    - numpy >=1.18.0,<2
    - pandas >=1.1,<1.1.5
    - scikit-learn >=0.23,<1
    - pytorch >=1.4,<2
    - torchvision >=0.5.0,<1
    - rdt >=0.2.10,<0.5

about:
  home: "https://github.com/sdv-dev/CTGAN"
  license: MIT
  license_family: MIT
  license_file:
  summary: "Conditional GAN for Tabular Data"
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - sdv-dev
